# Generated by Django 5.0.2 on 2024-02-22 03:05

import apart.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0003_city_rename_price_apart_price_month_apart_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartuniversity',
            name='image',
            field=apart.fields.CustomImageField(blank=True, null=True, upload_to='university_images/'),
        ),
    ]
