# Generated by Django 5.0.2 on 2024-02-22 05:51

import apart.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0004_alter_apartuniversity_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartimage',
            name='cover',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='apartimage',
            name='image',
            field=apart.fields.CustomImageField(upload_to='apart_images/'),
        ),
    ]
