# Generated by Django 5.0.2 on 2024-02-22 06:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0007_apart_add_by_apartbilldetail_add_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
