# Generated by Django 5.0.2 on 2024-02-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0009_rightssupport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apart',
            old_name='price_month',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='apart',
            name='price_season',
        ),
        migrations.RemoveField(
            model_name='apart',
            name='price_year',
        ),
        migrations.AddField(
            model_name='apart',
            name='price_type',
            field=models.CharField(blank=True, choices=[('month', 'Aylık'), ('year', 'Yıllık'), ('season', 'Sezonluk')], max_length=10, null=True),
        ),
    ]
