# Generated by Django 5.0.2 on 2024-02-25 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0010_rename_price_month_apart_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apart',
            name='price_type',
            field=models.CharField(blank=True, choices=[('Aylık', 'Month'), ('Yıllık', 'Year'), ('Sezonluk', 'Season')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='ApartDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yurume', models.IntegerField(blank=True, null=True)),
                ('otobus', models.IntegerField(blank=True, null=True)),
                ('tramvay', models.IntegerField(blank=True, null=True)),
                ('apart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances', to='apart.apart')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances', to='apart.apartuniversity')),
            ],
        ),
    ]
