# Generated by Django 5.0.2 on 2024-02-25 12:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0011_alter_apart_price_type_apartdistance'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartdistance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
