# Generated by Django 5.0.2 on 2024-02-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0013_apartfirm_apart_firma'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartfirm',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='firm_images/'),
        ),
        migrations.AlterField(
            model_name='apartimage',
            name='image',
            field=models.ImageField(upload_to='apart_images/'),
        ),
        migrations.AlterField(
            model_name='apartuniversity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='university_images/'),
        ),
    ]
