# Generated by Django 5.0.2 on 2024-02-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0015_apartfirm_add_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartfirm',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
