# Generated by Django 5.0.2 on 2024-02-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0016_apartfirm_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartfirm',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
