# Generated by Django 5.0.2 on 2024-03-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0018_alter_apartuniversity_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='apart',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
