# Generated by Django 5.0.2 on 2024-03-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0019_apart_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='apart',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
