# Generated by Django 5.0 on 2024-01-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_preview', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='email_token_used',
            field=models.BooleanField(default=False),
        ),
    ]
