# Generated by Django 5.0 on 2024-01-14 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_preview', '0004_userinfo_email_token_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='forget_password_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='forget_password_token_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
